init: panic kernel if init command fails

diff --git a/rootfs/common/init b/rootfs/common/init
--- a/rootfs/common/init
+++ b/rootfs/common/init
@@ -23,7 +23,11 @@ else
 fi
 
 if [ $# -ge 1 ]; then
-    "$@" || true
+    if ! "$@"; then
+        echo "command failed: $*"
+        sync
+        echo c > /proc/sysrq-trigger
+    fi
 else
     setsid -c -w /usr/bin/bash -l || true
 fi
